name: PlayerSearch
main: ss.linearlogic.playersearch.PlayerSearch
author: LinearLogic
version: 1.4
permissions:
    playersearch.lookup:
        description: Allows player to search for other players, both online and offline
        default: true
commands:
    lookup:
        aliases: [playersearch]